package crypt

const (
	errPrefix                        = "crypt: "
	errMsgFormat                     = "%s: %w"
	ErrorEmptyKeyPath                = errPrefix + "key path is empty"
	ErrorEmptyTombName               = errPrefix + "tomb name is empty"
	ErrorEmptyTombPath               = errPrefix + "tomb path is empty"
	ErrorEmptyTombsPath              = errPrefix + "tombs path is empty"
	ErrorInitializingTombsPath       = errPrefix + "initializing tombs path failed"
	ErrorInvalidPath                 = errPrefix + "path contains invalid characters"
	ErrorInvalidKeyPath              = errPrefix + "invalid key path"
	ErrorInvalidTombName             = errPrefix + "invalid tomb name"
	ErrorInvalidTombPath             = errPrefix + "invalid tomb path"
	ErrorInvalidTombsPath            = errPrefix + "invalid tombs path"
	ErrorMakingTombPathFailed        = errPrefix + "making tomb path failed"
	ErrorReadingTombFailed           = errPrefix + "reading tomb failed"
	ErrorWritingTombFailed           = errPrefix + "writing tomb failed"
	ErrorRemovingFileFailed          = errPrefix + "removing file failed"
	ErrorRemovingTombFailed          = errPrefix + "removing tomb failed"
	ErrorEncryptingTombFailed        = errPrefix + "encrypting tomb failed"
	ErrorDecryptingTombFailed        = errPrefix + "decrypting tomb failed"
	ErrorTombsPathIsDirectory        = errPrefix + "tombs path exists but is not a directory"
	ErrorTombNotFound                = errPrefix + "tomb not found"
	ErrorGettingTombsPathFilesFailed = errPrefix + "getting tombs from tombs path failed"
)
